version = 1

target = "http://192.70.89.113"
base = "http://147.196.152.4"
port = 9000
broker = "wsn/NotificationBroker"
wsdl = "data/NotificationBroker.wsdl"
default = "mine"

[dests]

  [dests.mine]

    broker = "localhost"
    name = "surv"
    type = "queue"

  [dests.swim02]

    broker = "swim02.eurocontrol.fr"
    name = "surv"
    type = "queue"
